### ISSUE TITLE
Can't be compatible with React?

### ISSUE THREAD

**Issue by UnsignedInt8** [Ragg-/three-mmd-loader#1]
Hello. I was trying to use your package in Reactjs app. But it could not resolve this package. 

```
Failed to compile
./node_modules/three-mmd-loader/dist/mmd-loader.js
Module not found: Can't resolve 'three' in 'node_modules/three-mmd-loader/dist'
```

And, please try to reproduce this problem by following these steps: 

1. New a test project
```
npm install -g create-react-app

create-react-app my-app --scripts-version=react-scripts-ts

cd my-app

npm i three-mmd-loader
```

2. Use `three-mmd-loader` in App.tsx
```
import { MMDLoader } from 'three-mmd-loader';

componentDidMount() {
let loader = new MMDLoader();
    loader.load('./miku.pmx', ['./hop-camera.vmd', './hop-motion.vmd']);
  }
```

3. Debug

```
npm start
```
Many errors would be outputted in console like this.

<img width="1194" alt="screen shot 2018-02-21 at 3 33 26 pm" src="https://user-images.githubusercontent.com/15274326/36468027-9dcfef76-171c-11e8-8138-75349975bd5e.png">

Please take some time to fix it, thanks.

**Comment by blue-bird1** [comment]
`yarn add  three`. Because the author did not add three.js to the dependency.
Have you succeeded with this repository?

**Comment by hanakla** [comment]
It is assumed that users of the library will use any version of three.js. As @blue-bird1 says, add three.js to the dependencies in your project.

Thanks.
